fail_fast: true
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
          - id: check-toml
          - id: check-yaml
          - id: check-json
          - id: check-xml
          - id: pretty-format-json
            args: ["--autofix"]
          - id: end-of-file-fixer
          - id: requirements-txt-fixer
          - id: end-of-file-fixer
          - id: trailing-whitespace
            language: python
    - repo: https://github.com/pre-commit/pygrep-hooks
      rev: v1.9.0 # Use the ref you want to point at
      hooks:
          - id: python-no-eval
          - id: python-no-log-warn
          - id: python-use-type-annotations
    - repo: https://github.com/asottile/pyupgrade
      rev: v2.24.0
      hooks:
          - id: pyupgrade
            args: [--py310-plus]
    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.9.2
      hooks:
          - id: flake8
    - repo: https://github.com/asottile/blacken-docs
      rev: v1.10.0
      hooks:
          - id: blacken-docs
    - repo: https://github.com/pre-commit/mirrors-scss-lint
      rev: v0.59.0
      hooks:
          - id: scss-lint
