# Generated by Django 3.2 on 2021-04-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telebot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botdata",
            name="data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
